### PR TITLE
Add ghc-8.10.3

### PR DESCRIPTION
**Pull request by jneira**
@Mistuke hi! i hope this pr might help a little bit, although changes are almost mechanical.
Feel free to close it if you have it already done.

### CODE REVIEW

**Comment by Mistuke** [comment]
Hi @jniera, thanks for the pr. I haven't made the package yet because I was waiting on an answer for https://mail.haskell.org/pipermail/ghc-devs/2020-December/019412.html

**Comment by jneira** [comment]
oh, I see, sorry for my ignorance, but are the choco package using that integer-simple tar? In any case I hope @bgamari will respond soon to start the ci machines 🙂

**Comment by jneira** [comment]
oh, I see, sorry for my ignorance, but are the choco package using that integer-simple tar? In any case I hope @bgamari will respond soon to start the ci machines 🙂

**Comment by Mistuke** [comment]
> oh, I see, sorry for my ignorance, but are the choco package using that integer-simple tar? In any case I hope @bgamari will respond soon to start the ci machines 🙂

Yes, the ghc 9.0 package which is the latest version adds among others support for integer-simple. The 8.10.3 is based off that to get support for the things added in the new scripts.

I pinged bgamari on IRC and got an answer and will remove integer-simple support and release it later today.

**Comment by Mistuke** [comment]
Thanks for the PR, since I've used a slightly newer template so I pushed a version myself this time. 18d9cb4495f85b726f9de6460243b52a0d22c1ac do appreciate it though!

**Pull request closed without merging**
